/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BitumenDakbedekkingRouteImport } from './routes/bitumen-dakbedekking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DakbedekkingVervangenRouteImport } from './routes/dakbedekking-vervangen'
import { Route as DakinspectieRouteImport } from './routes/dakinspectie'
import { Route as DaklekkageRouteImport } from './routes/daklekkage'
import { Route as DakonderhoudRouteImport } from './routes/dakonderhoud'
import { Route as DakrenovatieRouteImport } from './routes/dakrenovatie'
import { Route as DakreparatieRouteImport } from './routes/dakreparatie'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as EpdmDakbedekkingRouteImport } from './routes/epdm-dakbedekking'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as SpoedserviceRouteImport } from './routes/spoedservice'
import { Route as VacaturesRouteImport } from './routes/vacatures'
import { Route as ValbeveiligingRouteImport } from './routes/valbeveiliging'
import { Route as VveVastgoedbeheerRouteImport } from './routes/vve-vastgoedbeheer'
import { Route as NieuwsIndexRouteImport } from './routes/nieuws/index'
import { Route as NieuwsSlugRouteImport } from './routes/nieuws/$slug'
import { Route as ProjectenIndexRouteImport } from './routes/projecten/index'
import { Route as ProjectenSlugRouteImport } from './routes/projecten/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BitumenDakbedekkingRoute = BitumenDakbedekkingRouteImport.update({
  id: '/bitumen-dakbedekking',
  path: '/bitumen-dakbedekking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DakbedekkingVervangenRoute = DakbedekkingVervangenRouteImport.update({
  id: '/dakbedekking-vervangen',
  path: '/dakbedekking-vervangen',
  getParentRoute: () => rootRouteImport,
} as any)
const DakinspectieRoute = DakinspectieRouteImport.update({
  id: '/dakinspectie',
  path: '/dakinspectie',
  getParentRoute: () => rootRouteImport,
} as any)
const DaklekkageRoute = DaklekkageRouteImport.update({
  id: '/daklekkage',
  path: '/daklekkage',
  getParentRoute: () => rootRouteImport,
} as any)
const DakonderhoudRoute = DakonderhoudRouteImport.update({
  id: '/dakonderhoud',
  path: '/dakonderhoud',
  getParentRoute: () => rootRouteImport,
} as any)
const DakrenovatieRoute = DakrenovatieRouteImport.update({
  id: '/dakrenovatie',
  path: '/dakrenovatie',
  getParentRoute: () => rootRouteImport,
} as any)
const DakreparatieRoute = DakreparatieRouteImport.update({
  id: '/dakreparatie',
  path: '/dakreparatie',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const EpdmDakbedekkingRoute = EpdmDakbedekkingRouteImport.update({
  id: '/epdm-dakbedekking',
  path: '/epdm-dakbedekking',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoedserviceRoute = SpoedserviceRouteImport.update({
  id: '/spoedservice',
  path: '/spoedservice',
  getParentRoute: () => rootRouteImport,
} as any)
const VacaturesRoute = VacaturesRouteImport.update({
  id: '/vacatures',
  path: '/vacatures',
  getParentRoute: () => rootRouteImport,
} as any)
const ValbeveiligingRoute = ValbeveiligingRouteImport.update({
  id: '/valbeveiliging',
  path: '/valbeveiliging',
  getParentRoute: () => rootRouteImport,
} as any)
const VveVastgoedbeheerRoute = VveVastgoedbeheerRouteImport.update({
  id: '/vve-vastgoedbeheer',
  path: '/vve-vastgoedbeheer',
  getParentRoute: () => rootRouteImport,
} as any)
const NieuwsIndexRoute = NieuwsIndexRouteImport.update({
  id: '/nieuws/',
  path: '/nieuws/',
  getParentRoute: () => rootRouteImport,
} as any)
const NieuwsSlugRoute = NieuwsSlugRouteImport.update({
  id: '/nieuws/$slug',
  path: '/nieuws/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectenIndexRoute = ProjectenIndexRouteImport.update({
  id: '/projecten/',
  path: '/projecten/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectenSlugRoute = ProjectenSlugRouteImport.update({
  id: '/projecten/$slug',
  path: '/projecten/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bitumen-dakbedekking': typeof BitumenDakbedekkingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dakbedekking-vervangen': typeof DakbedekkingVervangenRoute
  '/dakinspectie': typeof DakinspectieRoute
  '/daklekkage': typeof DaklekkageRoute
  '/dakonderhoud': typeof DakonderhoudRoute
  '/dakrenovatie': typeof DakrenovatieRoute
  '/dakreparatie': typeof DakreparatieRoute
  '/diensten': typeof DienstenRoute
  '/epdm-dakbedekking': typeof EpdmDakbedekkingRoute
  '/over-ons': typeof OverOnsRoute
  '/spoedservice': typeof SpoedserviceRoute
  '/vacatures': typeof VacaturesRoute
  '/valbeveiliging': typeof ValbeveiligingRoute
  '/vve-vastgoedbeheer': typeof VveVastgoedbeheerRoute
  '/nieuws/$slug': typeof NieuwsSlugRoute
  '/projecten/$slug': typeof ProjectenSlugRoute
  '/nieuws/': typeof NieuwsIndexRoute
  '/projecten/': typeof ProjectenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bitumen-dakbedekking': typeof BitumenDakbedekkingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dakbedekking-vervangen': typeof DakbedekkingVervangenRoute
  '/dakinspectie': typeof DakinspectieRoute
  '/daklekkage': typeof DaklekkageRoute
  '/dakonderhoud': typeof DakonderhoudRoute
  '/dakrenovatie': typeof DakrenovatieRoute
  '/dakreparatie': typeof DakreparatieRoute
  '/diensten': typeof DienstenRoute
  '/epdm-dakbedekking': typeof EpdmDakbedekkingRoute
  '/over-ons': typeof OverOnsRoute
  '/spoedservice': typeof SpoedserviceRoute
  '/vacatures': typeof VacaturesRoute
  '/valbeveiliging': typeof ValbeveiligingRoute
  '/vve-vastgoedbeheer': typeof VveVastgoedbeheerRoute
  '/nieuws/$slug': typeof NieuwsSlugRoute
  '/projecten/$slug': typeof ProjectenSlugRoute
  '/nieuws': typeof NieuwsIndexRoute
  '/projecten': typeof ProjectenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bitumen-dakbedekking': typeof BitumenDakbedekkingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dakbedekking-vervangen': typeof DakbedekkingVervangenRoute
  '/dakinspectie': typeof DakinspectieRoute
  '/daklekkage': typeof DaklekkageRoute
  '/dakonderhoud': typeof DakonderhoudRoute
  '/dakrenovatie': typeof DakrenovatieRoute
  '/dakreparatie': typeof DakreparatieRoute
  '/diensten': typeof DienstenRoute
  '/epdm-dakbedekking': typeof EpdmDakbedekkingRoute
  '/over-ons': typeof OverOnsRoute
  '/spoedservice': typeof SpoedserviceRoute
  '/vacatures': typeof VacaturesRoute
  '/valbeveiliging': typeof ValbeveiligingRoute
  '/vve-vastgoedbeheer': typeof VveVastgoedbeheerRoute
  '/nieuws/$slug': typeof NieuwsSlugRoute
  '/projecten/$slug': typeof ProjectenSlugRoute
  '/nieuws/': typeof NieuwsIndexRoute
  '/projecten/': typeof ProjectenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bitumen-dakbedekking'
    | '/contact'
    | '/cookies'
    | '/dakbedekking-vervangen'
    | '/dakinspectie'
    | '/daklekkage'
    | '/dakonderhoud'
    | '/dakrenovatie'
    | '/dakreparatie'
    | '/diensten'
    | '/epdm-dakbedekking'
    | '/over-ons'
    | '/spoedservice'
    | '/vacatures'
    | '/valbeveiliging'
    | '/vve-vastgoedbeheer'
    | '/nieuws/$slug'
    | '/projecten/$slug'
    | '/nieuws/'
    | '/projecten/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bitumen-dakbedekking'
    | '/contact'
    | '/cookies'
    | '/dakbedekking-vervangen'
    | '/dakinspectie'
    | '/daklekkage'
    | '/dakonderhoud'
    | '/dakrenovatie'
    | '/dakreparatie'
    | '/diensten'
    | '/epdm-dakbedekking'
    | '/over-ons'
    | '/spoedservice'
    | '/vacatures'
    | '/valbeveiliging'
    | '/vve-vastgoedbeheer'
    | '/nieuws/$slug'
    | '/projecten/$slug'
    | '/nieuws'
    | '/projecten'
  id:
    | '__root__'
    | '/'
    | '/bitumen-dakbedekking'
    | '/contact'
    | '/cookies'
    | '/dakbedekking-vervangen'
    | '/dakinspectie'
    | '/daklekkage'
    | '/dakonderhoud'
    | '/dakrenovatie'
    | '/dakreparatie'
    | '/diensten'
    | '/epdm-dakbedekking'
    | '/over-ons'
    | '/spoedservice'
    | '/vacatures'
    | '/valbeveiliging'
    | '/vve-vastgoedbeheer'
    | '/nieuws/$slug'
    | '/projecten/$slug'
    | '/nieuws/'
    | '/projecten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BitumenDakbedekkingRoute: typeof BitumenDakbedekkingRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DakbedekkingVervangenRoute: typeof DakbedekkingVervangenRoute
  DakinspectieRoute: typeof DakinspectieRoute
  DaklekkageRoute: typeof DaklekkageRoute
  DakonderhoudRoute: typeof DakonderhoudRoute
  DakrenovatieRoute: typeof DakrenovatieRoute
  DakreparatieRoute: typeof DakreparatieRoute
  DienstenRoute: typeof DienstenRoute
  EpdmDakbedekkingRoute: typeof EpdmDakbedekkingRoute
  OverOnsRoute: typeof OverOnsRoute
  SpoedserviceRoute: typeof SpoedserviceRoute
  VacaturesRoute: typeof VacaturesRoute
  ValbeveiligingRoute: typeof ValbeveiligingRoute
  VveVastgoedbeheerRoute: typeof VveVastgoedbeheerRoute
  NieuwsSlugRoute: typeof NieuwsSlugRoute
  ProjectenSlugRoute: typeof ProjectenSlugRoute
  NieuwsIndexRoute: typeof NieuwsIndexRoute
  ProjectenIndexRoute: typeof ProjectenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitumen-dakbedekking': {
      id: '/bitumen-dakbedekking'
      path: '/bitumen-dakbedekking'
      fullPath: '/bitumen-dakbedekking'
      preLoaderRoute: typeof BitumenDakbedekkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dakbedekking-vervangen': {
      id: '/dakbedekking-vervangen'
      path: '/dakbedekking-vervangen'
      fullPath: '/dakbedekking-vervangen'
      preLoaderRoute: typeof DakbedekkingVervangenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dakinspectie': {
      id: '/dakinspectie'
      path: '/dakinspectie'
      fullPath: '/dakinspectie'
      preLoaderRoute: typeof DakinspectieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daklekkage': {
      id: '/daklekkage'
      path: '/daklekkage'
      fullPath: '/daklekkage'
      preLoaderRoute: typeof DaklekkageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dakonderhoud': {
      id: '/dakonderhoud'
      path: '/dakonderhoud'
      fullPath: '/dakonderhoud'
      preLoaderRoute: typeof DakonderhoudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dakrenovatie': {
      id: '/dakrenovatie'
      path: '/dakrenovatie'
      fullPath: '/dakrenovatie'
      preLoaderRoute: typeof DakrenovatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dakreparatie': {
      id: '/dakreparatie'
      path: '/dakreparatie'
      fullPath: '/dakreparatie'
      preLoaderRoute: typeof DakreparatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epdm-dakbedekking': {
      id: '/epdm-dakbedekking'
      path: '/epdm-dakbedekking'
      fullPath: '/epdm-dakbedekking'
      preLoaderRoute: typeof EpdmDakbedekkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoedservice': {
      id: '/spoedservice'
      path: '/spoedservice'
      fullPath: '/spoedservice'
      preLoaderRoute: typeof SpoedserviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacatures': {
      id: '/vacatures'
      path: '/vacatures'
      fullPath: '/vacatures'
      preLoaderRoute: typeof VacaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valbeveiliging': {
      id: '/valbeveiliging'
      path: '/valbeveiliging'
      fullPath: '/valbeveiliging'
      preLoaderRoute: typeof ValbeveiligingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vve-vastgoedbeheer': {
      id: '/vve-vastgoedbeheer'
      path: '/vve-vastgoedbeheer'
      fullPath: '/vve-vastgoedbeheer'
      preLoaderRoute: typeof VveVastgoedbeheerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nieuws/': {
      id: '/nieuws/'
      path: '/nieuws'
      fullPath: '/nieuws/'
      preLoaderRoute: typeof NieuwsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nieuws/$slug': {
      id: '/nieuws/$slug'
      path: '/nieuws/$slug'
      fullPath: '/nieuws/$slug'
      preLoaderRoute: typeof NieuwsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecten/': {
      id: '/projecten/'
      path: '/projecten'
      fullPath: '/projecten/'
      preLoaderRoute: typeof ProjectenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecten/$slug': {
      id: '/projecten/$slug'
      path: '/projecten/$slug'
      fullPath: '/projecten/$slug'
      preLoaderRoute: typeof ProjectenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BitumenDakbedekkingRoute: BitumenDakbedekkingRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DakbedekkingVervangenRoute: DakbedekkingVervangenRoute,
  DakinspectieRoute: DakinspectieRoute,
  DaklekkageRoute: DaklekkageRoute,
  DakonderhoudRoute: DakonderhoudRoute,
  DakrenovatieRoute: DakrenovatieRoute,
  DakreparatieRoute: DakreparatieRoute,
  DienstenRoute: DienstenRoute,
  EpdmDakbedekkingRoute: EpdmDakbedekkingRoute,
  OverOnsRoute: OverOnsRoute,
  SpoedserviceRoute: SpoedserviceRoute,
  VacaturesRoute: VacaturesRoute,
  ValbeveiligingRoute: ValbeveiligingRoute,
  VveVastgoedbeheerRoute: VveVastgoedbeheerRoute,
  NieuwsSlugRoute: NieuwsSlugRoute,
  ProjectenSlugRoute: ProjectenSlugRoute,
  NieuwsIndexRoute: NieuwsIndexRoute,
  ProjectenIndexRoute: ProjectenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
